# Generated by Django 5.0.7 on 2024-07-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_processeddata_delete_inferreddatatype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processeddata',
            old_name='data_type',
            new_name='inferred_type',
        ),
    ]
